# Generated by Django 4.2.3 on 2023-08-08 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetcategory',
            old_name='typical_raw_amount',
            new_name='typical_monthly_amount',
        ),
    ]
